### ISSUE TITLE
Forms need CSRF tokens

### ISSUE THREAD

**Issue by jezen** [riskbook/yesod-auth-simple#1]
The forms are currently vulnerable to CSRF. Should use the tokens from yesod-form to fix this.

**Comment by timds** [comment]
Closed for now as the password-involving fields now use CSRF tokens. Other forms like requesting a reset and entering your email address still don't use the tokens. I'm not sure there's much damage that an attacker could do by those other forms plus I also wanted to get a better idea of how CSRF protection in this library will play out in interaction with protection in apps themselves.
